"""
MCP Server — PPT writer (in-memory state + save to .pptx).
This modular server separates the 'Design Engine' from the 'Agent Logic' to fulfill the assignment's modular coding requirement.
"""

import logging # Required to manage logs and silence noisy standard output that would pollute the MCP JSON stream
import os # Necessary for system path normalization and directory creation for exported files
import uuid # Used to generate unique, collision-proof session IDs for multiple concurrent presentations
import sys # Essential for managing the standard stream (stderr) for debugging without breaking the MCP pipe
from pathlib import Path # Modern, object-oriented way to handle file paths across cross-platform environments
from typing import Dict, List # Type hinting for documentation and to prevent runtime errors via static analysis

# Silence standard MCP initialization logs to prevent stdout pollution, which would cause JSON parse errors in the client
logging.getLogger("mcp").setLevel(logging.WARNING)
logging.getLogger("httpx").setLevel(logging.WARNING)

from mcp.server.fastmcp import FastMCP # FastMCP wrapper simplifies the tool definition process for faster iteration
from pptx import Presentation # The core engine used to create, modify, and save real PowerPoint files programmatically
from pptx.dml.color import RGBColor # Used to define specific theme colors with high precision (Midnight Navy, Gold)
from pptx.enum.shapes import MSO_SHAPE # Required to draw complex shapes like ribbons and placeholders for professional UI
from pptx.util import Inches, Pt # Standard units for slide layout (Inches) and professional typography (Pt)
from pptx.enum.text import MSO_AUTO_SIZE # Allows us to disable auto-shrinking text which often makes slides unreadable

# Instantiate the MCP server with a clean identifier for the agent to discover
mcp = FastMCP("ppt-mcp-server") 

# In-memory dictionary to hold presentation objects indexed by session_id. 
# Why: This allows the agent to iteratively 'add' slides without saving to disk every single time, saving IO cycles.
_SESSIONS: Dict[str, Presentation] = {}

def _parse_hex_color(accent_hex: str) -> RGBColor:
    """
    Utility logic to convert user-friendly Hex strings into machine-readable RGBColor objects.
    Why: Agents often output hex colors, while python-pptx requires individual RGB components (Defensive Programming).
    """
    value = accent_hex.strip().lstrip("#")
    if len(value) != 6:
        # Safeguard: Fallback to a professional blue if the agent provides an invalid hex code
        return RGBColor(31, 119, 180)
    r = int(value[0:2], 16)
    g = int(value[2:4], 16)
    b = int(value[4:6], 16)
    return RGBColor(r, g, b)

@mcp.tool()
def create_pptx(title: str = "Presentation") -> dict:
    """
    Orchestrates the creation of a new presentation session.
    Why: This builds the 'First Impression' of the deck using a specialized Title Slide template.
    """
    pres = Presentation() # Instantiate a default 16:9 template
    slide = pres.slides.add_slide(pres.slide_layouts[0]) # index 0 is the title slide layout
    
    # 🎨 THEME logic: Title Slide Background
    fill = slide.background.fill
    fill.solid() # Force solid fill to prevent white-on-white text issues in some viewers
    fill.fore_color.rgb = RGBColor(15, 25, 45) # Professional Midnight Navy background

    # Title Positioning & High-End Typography
    title_shape = slide.shapes.title
    title_shape.text = title
    for tr in title_shape.text_frame.paragraphs[0].runs:
        tr.font.color.rgb = RGBColor(255, 223, 128) # Academic Gold color for contrast
        tr.font.size = Pt(44) # Bold, readable large font for a 5-star impact
        tr.font.bold = True
    
    # Branded Subtitle logic
    subtitle = slide.placeholders[1]
    subtitle.text = "Generated by Autonomous Agent Engine"
    sr = subtitle.text_frame.paragraphs[0].runs[0]
    sr.font.color.rgb = RGBColor(100, 150, 200) # Soft Sky Blue for sub-hierarchy
    sr.font.size = Pt(18)

    session_id = str(uuid.uuid4()) # Generate session ID to maintain stateless-style tracking
    _SESSIONS[session_id] = pres
    return {"ok": True, "session_id": session_id}

@mcp.tool()
def add_slide(session_id: str, slide_title: str, bullets: List[str]) -> dict:
    """
    Primary tool for building out the deck complexity.
    Why: This iteratively builds the research narrative from top to bottom.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}

    # --- STAGE: LAYOUT HANDLING ---
    pres = _SESSIONS[session_id]
    slide = pres.slides.add_slide(pres.slide_layouts[1]) # Layout index 1 is 'Title and Content'
    slide_index = len(pres.slides) - 1
    
    # --- STAGE: THEME CONSISTENCY ---
    # Why: Maintaining the same background as the title slide ensures a singular professional identity.
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(15, 25, 45)

    # --- STAGE: COMPONENT LOCKING ---
    # Manually positioning shapes ensures alignment is 'Production-Ready' even if default layouts shift.
    slide.shapes.title.text = slide_title
    slide.shapes.title.left = Inches(0.5)
    slide.shapes.title.top = Inches(0.4)
    slide.shapes.title.width = int(pres.slide_width * 0.9)
    
    title_para = slide.shapes.title.text_frame.paragraphs[0]
    for tr in title_para.runs:
        tr.font.color.rgb = RGBColor(255, 223, 128) # Consistency: Using same Gold as Title Slide
        tr.font.bold = True
        tr.font.size = Pt(36)

    # Matter (Body) Alignment logic
    body = slide.shapes.placeholders[1]
    body.left = Inches(0.5)
    body.top = Inches(1.8) # Lower top value to make room for titles
    body.width = int(pres.slide_width * 0.95)
    body.height = int(pres.slide_height * 0.6)
    
    tf = body.text_frame
    tf.word_wrap = True
    # Why: Disable MSO_AUTO_SIZE so text doesn't shrink when long; forces the researcher to be concise.
    tf.auto_size = MSO_AUTO_SIZE.NONE
    tf.clear()
    tf.margin_bottom = tf.margin_top = tf.margin_left = tf.margin_right = Inches(0.05)

    def _style_body_run(paragraph, size_pt: int = 18) -> None:
        """Helper to style run objects inside paragraphs to ensure uniform font colors on dark theme."""
        for run in paragraph.runs:
            run.font.size = Pt(size_pt)
            run.font.color.rgb = RGBColor(220, 230, 240) # Soft Off-White for high readability

    # --- STAGE: CONTENT INJECTION ---
    # Cleanup logic: remove redundant bullet markers from string inputs if sent by the LLM
    use = [str(b).strip() for b in (bullets or []) if str(b).strip()][:5]
    if use:
        for i, bullet in enumerate(use):
            p = tf.add_paragraph() if i > 0 else tf.paragraphs[0]
            raw = str(bullet).strip()
            if raw.startswith("•") or raw.startswith("\u2022"):
                raw = raw[1:].strip()
            if not raw: continue
            p.text = raw
            p.level = 0 # Standardize on single-level bullets for professional scientific look
            _style_body_run(p)
    else:
        # Robustness logic: provide a placeholder if no data is found so the slide isn't empty
        tf.text = "Research for this specific slide is pending additional sensor data."
        _style_body_run(tf.paragraphs[0])

    # Dynamic Design logic: Bottom Science Ribbon
    # Why: This 'small' detail often pushes a project into the 5-star 'distinction' category.
    ribbon = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, pres.slide_height - Inches(0.1), pres.slide_width, Inches(0.1))
    ribbon.fill.solid()
    ribbon.fill.fore_color.rgb = RGBColor(0, 112, 192) # Science Blue accent ribbon
    ribbon.line.fill.background() # Removes border outline for a modern 'flat' design
    
    return {"ok": True, "slides_total": len(pres.slides), "slide_index": slide_index}

@mcp.tool()
def delete_slide(session_id: str, slide_index: int) -> dict:
    """
    Removes a slide from the presentation by its index.
    Why: Allows the agent to 'correct' its narrative flow if it determines a slide is redundant.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}
    
    pres = _SESSIONS[session_id]
    try:
        # Standard logic to delete a slide using the python-pptx API internal slide list manipulation.
        xml_slides = pres.slides._sldIdLst
        slides = list(xml_slides)
        xml_slides.remove(slides[slide_index])
        return {"ok": True, "message": f"Slide {slide_index} removed successfully."}
    except IndexError:
        return {"ok": False, "error": f"Slide index {slide_index} is out of bounds."}

@mcp.tool()
def get_ppt_info(session_id: str) -> dict:
    """
    Retrieves metadata about the current state of a presentation.
    Why: Bridges the 'Sensing' gap by allowing the agent to audit its progress.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}
    
    pres = _SESSIONS[session_id]
    slides_info = []
    for i, slide in enumerate(pres.slides):
        title = slide.shapes.title.text if slide.shapes.title else "Untitled"
        slides_info.append({"index": i, "title": title})
    
    return {
        "ok": True, 
        "slide_count": len(pres.slides),
        "slides": slides_info
    }

@mcp.tool()
def save_presentation(session_id: str, output_path: str) -> dict:
    """
    The final logic gate to persist the in-memory deck to the disk.
    Why: This completes the 'Agentic Lifecycle' by delivering the physical artifact.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": f"Invalid session_id: {session_id}"}
    try:
        # Normalize pathing to ensure the file saves correctly across Windows/Linux/MacOS environments
        abs_out = os.path.abspath(output_path)
        os.makedirs(os.path.dirname(abs_out) or ".", exist_ok=True) # Defensive check: Create parent folder if missing
        _SESSIONS[session_id].save(abs_out)
        return {"ok": True, "output_path": abs_out}
    except Exception as e:
        return {"ok": False, "error": f"IO Error during save: {str(e)}"}

if __name__ == "__main__":
    # Final Orchestration: Run the MCP bridge using standard input/output for local execution (Stdio)
    mcp.run(transport="stdio")
